### ISSUE TITLE
Glass search is not appearing

### ISSUE THREAD

**Issue by NuncaLoUsen** [mennooo/orclapex-modal-lov#18] opened 2018-06-14 02:03 UTC
Hi,

Can you help me? Glass search is not appearing.

![imagen](https://user-images.githubusercontent.com/9569208/41387568-2c37802a-6f4d-11e8-9734-fa6014e7e70f.png)

Thanks for your help.

Jairo.

**Comment by mennooo** [comment] 2018-08-02 07:26
Hi,

1. Are you using the universal theme?
2. Are you using a custom icon library?

**Comment by mennooo** [comment] 2018-08-09 10:06
I've fixed this for fontawesome, should also work for this issue. Next version will be released soon.

**Comment by mennooo** [comment] 2018-08-09 10:11
Duplicate of #30

**Closed by mennooo** 2018-08-09 10:11 UTC
Labels: help wanted
